shellEmulator: true

trustPolicy: no-downgrade

packages:
  - apps/*
  - packages/*

autoInstallPeers: true

catalogs:
  dev:
    '@antfu/eslint-config': ^7.7.0
    '@commitlint/cli': ^20.4.1
    '@commitlint/config-conventional': ^20.4.1
    '@iconify-json/lucide': ^1.2.88
    '@iconify-json/simple-icons': ^1.0.0
    bumpp: ^11.0.1
    eslint: ^9.39.2
    husky: ^9.1.7
    nano-staged: ^0.9.0
    nuxt: ^4.4.2
    tailwindcss: ^4.2.1
    tailwindcss-motion: ^1.1.1
    typescript: ^5.9.3
    vite: ^7.3.1
    vue-tsc: ^3.2.4
  integrations:
    '@nuxt/ui': ^4.5.1
    '@nuxtjs/i18n': ^10.2.3
    '@nuxtjs/robots': ^5.7.1
    '@nuxtjs/sitemap': ^7.2.8
    '@vueuse/core': ^14.2.0
    '@vueuse/nuxt': ^14.2.0
    nuxt-live-cursors: ^0.1.0
  test:
    '@playwright/test': ^1.52.0
    '@vitest/coverage-v8': ^4.1.0
    vitest: ^4.1.0
  types:
    '@types/node': ^25.5.0
