apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: kosarev-space
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: ghcr.io/hmbanan666/kosarev-web-app:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: web-app-secrets
          env:
            - name: NODE_ENV
              value: production
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
